name: Bug report
description: Report a bug in Terrain3D
body:

- type: markdown
  attributes:
    value: |
      - Please your issue hasn't been addressed in the documentation: [Troubleshooting](https://github.com/TokisanGames/Terrain3D/wiki/Troubleshooting), [Tips](https://github.com/TokisanGames/Terrain3D/wiki/Tips), [Setting up textures](https://github.com/TokisanGames/Terrain3D/wiki/Setting-Up-Textures), and other pages.
      - The following fields will help you provide the information we need to resolve the issue.

- type: input
  attributes:
    label: Godot version
    description: >
      Specify the exact version of Godot. Inside Godot, click the version shown on the bottom bar to copy it.
    placeholder: v4.1.2.stable.official [399c9dc39]
  validations:
    required: 'true'

- type: input
  attributes:
    label: Terrain3D version
    description: >
      Specify the version of Terrain3D. Either the name of a release, or the commit string if using a development build.
    placeholder: v0.8.3-alpha_gd4.1.1
  validations:
    required: 'true'

- type: input
  attributes:
    label: System information
    description: |
      - Specify the OS version, GPU and rendering backend (Vulkan Forward+, Mobile, Compatibility/WebGL).
      - **Starting with Godot 4.1, you can copy this information to your clipboard by using *Help > Copy System Info* at the top of the editor window.**
    placeholder: Windows 10/64 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia, 510.85.02)
  validations:
    required: 'true'

- type: dropdown
  id: demo
  attributes:
    label: Is the issue reproducable in the demo?
    description: |
      Try to isolate the problem. E.g. If you're having issues with a texture, put it in the demo and see if it causes the same issue.
    options:
      - Yes
      - No
      - Not applicable
  validations:
    required: 'true'

- type: textarea
  attributes:
    label: Issue description
    description: |
      Describe your issue briefly. What doesn't work, what are you expecting, and what have you tried for troubleshooting?
      You can paste or drag in images or videos. Format code with <code>```</code> before and after on their own lines.
  validations:
    required: 'true'
    
- type: textarea
  attributes:
    label: Logs
    description: |
      Terrain3D has [extensive logging](https://github.com/TokisanGames/Terrain3D/wiki/Troubleshooting#debug-logs). Enable it and attach a text file, or copy the logs here. 
      Format them with <code>```</code> before and after on their own lines.
  validations:
    required: 'false'
    
