name: 🤖 Android Builds
on: [ workflow_call, workflow_dispatch ]

env:
    SCONSFLAGS: verbose=yes

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: android-debug
            name: Android Debug
            runner: ubuntu-20.04
            target: template_debug
            platform: android
            arch: arm64
          - identifier: android-release
            name: Android Release
            runner: ubuntu-20.04
            target: template_release
            platform: android
            arch: arm64

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: (Android) Set up Android dependencies
        uses: ./.github/actions/android-deps

      - name: Setup python & scons
        uses: ./.github/actions/base-deps

      - name: Compile extension
        shell: sh
        env:
            SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
            SCONS_CACHE_LIMIT: 7168
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' ${{ env.SCONSFLAGS }} -j2

      - name: Prepare artifact
        shell: sh
        run: |
          ls -l project/addons/terrain_3d/bin/
          cp --no-clobber '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE' ${{ github.workspace }}/project/addons/terrain_3d/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/project/
