name: 🐧 Linux Builds
on: [ workflow_call, workflow_dispatch ]

env:
    SCONSFLAGS: verbose=yes

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: linux-debug
            name: Linux Debug
            target: template_debug
            platform: linux
            arch: x86_64
          - identifier: linux-release
            name: Linux Release
            target: template_release
            platform: linux
            arch: x86_64

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup python & scons
        uses: ./.github/actions/base-deps

      - name: Setup build cache
        uses: ./.github/actions/build-cache
        with:
          cache-name: ${{ matrix.identifier }}
        continue-on-error: true

      - name: Compile extension
        shell: sh
        env:
            SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
            SCONS_CACHE_LIMIT: 7168
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' ${{ env.SCONSFLAGS }} -j2

      - name: Prepare artifact
        shell: sh
        run: |
          ls -l project/addons/terrain_3d/bin/
          strip project/addons/terrain_3d/bin/libterrain.*
          ls -l project/addons/terrain_3d/bin/
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE' ${{ github.workspace }}/project/addons/terrain_3d/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/project/
