name: 🍎 macOS Builds
on: [ workflow_call, workflow_dispatch ]

env:
    SCONSFLAGS: verbose=yes

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS Debug
            target: template_debug
            platform: macos
          - name: macOS Release
            target: template_release
            platform: macos

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup python & scons
        uses: ./.github/actions/base-deps

      - name: Compile extension
        shell: sh
        env:
            SCONS_CACHE: "${{ github.workspace }}/.scons-cache/"
            SCONS_CACHE_LIMIT: 7168
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' ${{ env.SCONSFLAGS }} -j2

      - name: Prepare artifact
        shell: sh
        run: |
          ls -l project/addons/terrain_3d/bin/*/
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE' ${{ github.workspace }}/project/addons/terrain_3d/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/project/